config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get '/mypage', to: 'users#show'
  root 'users#show'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :users, only:[:show]
  resources :routes do
    collection do
      patch :update_order
    end
    resources :route_spots, only:[:index, :edit, :update, :show] do
      collection do
        patch :update_order
      end
    end
  end
  resources :spots do
    collection do
      patch :update_order
    end
  end


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/spot.rb
class Spot < ApplicationRecord
  # include MultipleUpdate

  belongs_to :user
  has_many :route_spots, dependent: :destroy
  has_many :routes, through: :route_spots

  validates :name, presence: true, length: { maximum: 20 }
  validates :address, presence: true
  validates :tel, presence: true, format: { with: VALID_PHONE_REGEX }

  scope :and_routes, -> { eager_load(:routes).order(sequence: "ASC")}
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_id, only: %i[edit destroy update show]
  before_action :set_routes, only: %i[new edit]
  def index
    @user = current_user
    @spots = current_user.spots.order(id: "DESC").page(params[:page]).per(4)
  end

  def show
  end

  def new
    @spot = Spot.new
  end

  def create
    @spot = current_user.spots.new(spot_params)
    if @spot.save
      redirect_to spots_path, notice: "「#{@spot.name}」を登録しました"
    else
      render :new
    end
  end

  def edit
    @have_routes = @spot.routes.ids
  end

  def update
    if @spot.update(spot_params)
      redirect_to spots_path(anchor: "id_#{@spot.id}"), notice: "「#{@spot.name}」を編集しました"
    else
      render :new
    end
  end

  def destroy
    if
      @spot.destroy
      redirect_to spots_path, notice: "「#{@spot.name}」を削除しました"
    else
      render spots_path, alert: "「#{@spot.name}」を削除する権限がありません"
    end
  end

  # def update_order
  #   spot.multi_update(routes_params, :routes)
  # end

  private
  def spot_params
    params.require(:spot).permit(:id, :name, :address, :tel, :memo, route_ids:[])
  end
  # def spots_params
  #   params.permit(spots: :sequence)
  # end

  def set_id
    @spot = Spot.find(params[:id])
  end
  def set_routes
    @my_routes = current_user.routes.order(sequence: "ASC")
  end

end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/_form.html.slim
= form_with model: spot, local:true, id:"spot_form" do |f|
  .form-group
    = f.label :name
    = f.text_field :name, id: 'spot_name'
    = f.label :address
    = f.text_field :address, id: 'spot_address'
    = f.label :tel
    = f.text_field :tel, id: 'spot_tel'
    = f.label :memo
    = f.text_area :memo, placeholder:'全ルート共通の内容', id: 'spot_memo'
    = f.label "ルート" do
      span ルート
      span#route_count
        = " (#{spot.routes.size})"
    ul#spot_routes

      - @my_routes.each do |route|
        - if @my_routes&.include?(route.id)
          li.btn_route data=route.id
             div.checkbox_on
              span.route_sequence #{route.sequence}
              span.route_name #{route.name}
        - elsif @my_routes != nil
          li.btn_spot data=route.id
            div
              span.route_sequence #{route.sequence}
              span.route_name #{route.name}

  span#hidden_routes
    = f.collection_check_boxes(:route_ids, @my_routes, :id, :name)
  div.button_box
    = f.submit '登録する' , class:'button-primary'
    - unless spot.id == nil
      = link_to "削除", {:controller => :spots, :action => 'destroy', :id => spot.id }, :method => :delete, data: { confirm: "本当に「#{spot.name}」 を削除しますか？" }, class:'button button-primary'

app/views/spots/edit.html.slim
- @spot.errors.any?
  = render partial: 'shared/errors', locals: { object: @spot }
= render partial: 'form', locals: { spot: @spot }

app/views/spots/index.html.slim
h1 スポット一覧
= render partial: 'shared/notice'
= link_to new_spot_path, class:'button button-secondary w_full' do
  i.fas.fa-pencil-alt
  span 新規スポットを作成
- if @spots.size >= 1
  div.spot_list
    = form_with(url: update_order_spots_path, local: true, method: :patch, id:'sort_form') do
      ul
        - @spots.each do |spot|
          = fields_for "spots[]", spot do |f|
            li id="id_#{spot.id}"
              h2
                span.sequence
                  = spot.id
                span.title #{spot.name}
              dl.spot_profile
                dt 住所
                dd
                  = link_to "https://maps.google.co.jp/maps/search/#{spot.address}" do
                    i.fas.fa-map-marker-alt
                    = spot.address
                dt TEL
                dd
                  = link_to "tel:#{spot.tel}" do
                    i.fas.fa-phone-volume
                    = spot.tel
              - if spot.routes.present?
                ul.route_tag
                  - spot.routes.each do |route|
                    li #{route.name}
              - if spot.memo.present?
                div.btn_acordion.button.button-secondary
                  span メモ
                  i.fas.fa-chevron-down
                span.memo.close
                  = simple_format(spot.memo)
              div.bottom
                = link_to edit_spot_path(spot.id), class:'button button-secondary' do
                  i.fas.fa-edit
                  span 編集
                / = link_to spot_path(spot.id), class:'button button-secondary' do
                /   i.fas.fa-list-ol
                /   span 見る
                div.edited
                  span 更新：
                  span
                    = l(spot.updated_at, format: :long)
  = paginate @spots
- else
  div.list_empty 登録されたスポットがありません。

app/views/spots/new.html.slim
- @spot.errors.any?
  = render partial: 'shared/errors', locals: { object: @spot }
= render partial: 'form', locals: { spot: @spot }

app/views/spots/show.html.slim
= render partial: 'shared/notice'

h4 #{@spot.name}