config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get '/mypage', to: 'users#show'
  root 'users#show'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :users, only:[:show]
  resources :routes do
    collection do
      patch :update_order
    end
    resources :route_spots, only:[:index, :edit, :update, :show] do
      collection do
        patch :update_order
      end
    end
  end
  resources :spots do
    collection do
      patch :update_order
    end
  end


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/route_spot.rb
class RouteSpot < ApplicationRecord
  include MultipleUpdate
  belongs_to :route
  belongs_to :spot

  before_validation :set_sequence

  private
    def set_sequence
      if sequence.nil?
        self.sequence = (self.route.route_spots.maximum("sequence") != nil ? self.route.route_spots.maximum("sequence") + 1 : 1)
      end
    end
end

app/controllers/route_spots_controller.rb
class RouteSpotsController < ApplicationController
  require 'time'
  def index
    @route = current_user.routes.find(params[:route_id])
    @route_spots = @route.route_spots.eager_load(:spot).order(:sequence)
  end

  def show
    @route = current_user.routes.find(params[:route_id])
    @route_spots = @route.route_spots.eager_load(:spot).order(:sequence)
  end

  def update_order
    RouteSpot.multi_update(route_spots_params, :route_spots)
    # redirect_to route_route_spots_path(params[:route_id])
    redirect_to route_path(params[:route_id])
  end

  private
  def route_spots_params
    params.permit(route_spots: [:sequence, :arrival, :volume, :memo])
  end
end

app/helpers/route_spots_helper.rb
module RouteSpotsHelper
end

app/views/route_spots/index.html.slim
h1
  span 経路を編集
  span.subtitle #{@route.name}
div.route_spots_list
  = link_to edit_route_path(@route.id), class:'button button-secondary w_full' do
    i.fas.fa-pencil-alt
    span 中継地点を追加
  - if @route_spots.size >= 1
    = form_with(url: update_order_route_route_spots_path, local: true, method: :patch, id:'sort_form') do
      ul.sortableArea2
        - @route_spots.each do |route_spot|
          = fields_for "route_spots[]", route_spot do |f|
            li id="id_#{route_spot.id}"
              h2
                span.sequence
                  = route_spot.sequence.present? == true ? "#{route_spot.sequence}" : '--'
                span #{route_spot.spot.name}
                i.fas.fa-arrows-alt-v.move_icon
              div.box_line
                div
                  = f.label :arrival
                  / input type="text" name="route_spots[#{route_spot.id}][arrival]" class="timepicker" id="route_spots_#{route_spot.id}_arrival"

                  = f.text_field :arrival, class: 'route_spot_arrival timepicker form_arrival'
                div
                  = f.label :volume
                  = f.text_field :volume, class: 'route_spot_volume form_volume'
              div.box_bottom
                = f.label :memo, class:'tag_route_spot_memo'
                = f.text_area :memo, placeholder:"#{@route.name}について", class: 'route_spot_memo'
              = f.hidden_field :sequence, class:'form_sequence'
      div.button_box.btn2
        = link_to '戻る', routes_path, class:'button button-primary'
        = submit_tag '登録する' , class:'button-primary'
  - else
    div.list_empty 登録された中継地点がありません。