config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get '/mypage', to: 'users#show'
  root 'users#show'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :users, only:[:show]
  resources :routes do
    collection do
      patch :update_order
    end
    resources :route_spots, only:[:index, :edit, :update, :show] do
      collection do
        patch :update_order
      end
    end
  end
  resources :spots do
    collection do
      patch :update_order
    end
  end


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/route.rb
class Route < ApplicationRecord
  include MultipleUpdate
  belongs_to :user
  has_many :route_spots, dependent: :destroy
  has_many :spots, through: :route_spots


  validates :name, presence: true, length: { maximum: 20 }

  scope :and_spots, -> { eager_load(:spots).order(name: "ASC")}

  # def self.multi_update(routes_params)
  #   routes_params.to_h[:routes].map do |id, attributes|
  #     route = self.find(id)
  #     route.update_attributes!(attributes)
  #   end
  # end
  before_validation :set_sequence
  after_destroy :align_route_sequence
  after_update :align_route_spots_sequence

  private
    def set_sequence
      if sequence.nil?
        self.sequence = (self.user.routes.size >= 1 ? self.user.routes.maximum("sequence") + 1 : 1)
      end
    end
    def align_route_sequence
      items = self.user.routes.order(sequence: "ASC", id:"DESC")
      align_object(items)
    end
    def align_route_spots_sequence
      items = self.route_spots.order(sequence: "ASC", id:"DESC")
      align_object(items)
    end

    def align_object(items)
      items.each_with_index{ |item,index|
        item.sequence = index + 1
        item.save
      }
    end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_id, only: %i[edit destroy update show]
  before_action :set_spots, only: %i[new edit]

  def index
    @user = current_user
    @routes = current_user.routes.order(sequence: "ASC", id:"DESC")
  end

  def show
    @spots = @route.route_spots.eager_load(:spot).order(:sequence).page(params[:page]).per(20)
  end

  def new
    @route = Route.new
    # @route.sequence = (current_user.routes != nil ? current_user.routes.maximum("sequence") + 1 : 1)
  end

  def create
    @route = current_user.routes.new(route_params)
    if @route.save
      redirect_to routes_path, notice: "「#{@route.name}」を登録しました"
    else
      render :new
    end
  end

  def edit
    @have_spots = @route.spots.ids
  end

  def update
    if @route.update(route_params)
      redirect_to routes_path(anchor: "id_#{@route.id}"), notice: "「#{@route.name}」を編集しました"
    else
      render :edit
    end
  end

  def destroy
    if
      @route.destroy
      redirect_to routes_path, notice: "「#{@route.name}」を削除しました"
    else
      render routes_path, alert: "「#{@route.name}」を削除する権限がありません"
    end
  end

  def update_order
    Route.multi_update(routes_params, :routes)
  end

  private
  def route_params
    params.require(:route).permit(:id, :name, :memo, :sequence, spot_ids:[])
  end
  def routes_params
    params.permit(routes: :sequence)
  end

  def set_id
    @route = Route.find(params[:id])
  end

  def set_spots
    @my_spots = current_user.spots
  end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_form.html.slim
= form_with model: route, local:true, id:"route_form" do |f|
  .form-group
    = f.label :name
    = f.text_field :name, id: 'route_name'
    = f.label :memo
    = f.text_area :memo, id: 'route_memo'
    = f.hidden_field :sequence, id: 'route_sequence'
    = f.label "中継地点" do
      span 中継地点
      span#spot_count
        = " (#{route.spots.size})"
    ul#route_spots
      - @my_spots.each do |spot|
        - if @have_spots&.include?(spot.id)
          li.btn_spot data=spot.id
             div.checkbox_on
              span.spot_id ID:#{spot.id}
              span.spot_name #{spot.name}
              span.spot_address #{spot.address}
        - elsif @have_spots != nil
          li.btn_spot data=spot.id
            div
              span.spot_id ID:#{spot.id}
              span.spot_name #{spot.name}
              span.spot_address #{spot.address}
    span#hidden_spots
      = f.collection_check_boxes(:spot_ids, @my_spots, :id, :name)
  div.button_box.btn3
    = link_to '戻る', routes_path, class:'button button-primary'
    = f.submit '登録する' , class:'button-primary'
    - unless route.id == nil
      = link_to "削除", {:controller => :routes, :action => 'destroy', :id => route.id }, :method => :delete, data: { confirm: "本当に「#{route.name}」 を削除しますか？" }, class:'button button-primary'

app/views/routes/edit.html.slim
- @route.errors.any?
  = render partial: 'shared/errors', locals: { object: @route }
h1
  span ルート情報を編集
  span.subtitle #{@route.name}
= render partial: 'form', locals: { route: @route }

app/views/routes/index.html.slim
h1 配送ルート一覧

= render partial: 'shared/notice'
= link_to new_route_path, class:'button button-secondary w_full' do
  i.fas.fa-pencil-alt
  span 新規ルートを作成
- if @routes.size >= 1
  div.route_list
    = form_with(url: update_order_routes_path, local: true, method: :patch, id:'sort_form') do
      ul.sortableArea
        - @routes.each do |route|
          = fields_for "routes[]", route do |f|
            li id="id_#{route.id}"
              = link_to route_path(route.id) do
                h2
                  span.sequence
                    = route.sequence.present? == true ? "#{route.sequence}" : '--'
                  span.title #{route.name}
                  i.fas.fa-arrows-alt-v.move_icon
                - if route.memo.present?
                  span.memo
                    = simple_format(route.memo)
              div.bottom
                = link_to edit_route_path(route.id), class:'button button-secondary' do
                  i.fas.fa-edit
                  span 編集
                = link_to route_route_spots_path(route.id), class:'button button-secondary' do
                  i.fas.fa-list-ol
                  span 経路編集
                div.edited
                  span 更新：
                  span
                    = l(route.updated_at, format: :long)
              = f.hidden_field :sequence, class:'form_sequence'
- else
  div.list_empty 登録されたルートがありません。

app/views/routes/new.html.slim
- @route.errors.any?
  = render partial: 'shared/errors', locals: { object: @route }
= render partial: 'form', locals: { route: @route }

app/views/routes/show.html.slim
= render partial: 'shared/notice'

div#route_profile
  h1
    = @route.name
  div#route_memo
    = simple_format(@route.memo)
  div#spot_list
    = paginate @spots
    ul
      - @spots.each do |item|
        li id="spot_#{item.id}"
          header
            span.sequence #{item.sequence}
            span.arrival #{item.arrival}
            span.name #{item.spot.name}
            - if item.spot.memo.present? || item.memo.present?
              span.icon_button data-id="#{item.id}"
                i.fas.fa-sticky-note
          div.detail
            div
              = link_to "https://maps.google.co.jp/maps/search/#{item.spot.address}" do
                i.fas.fa-map-marker-alt
                = item.spot.address
            div
              = link_to "tel:#{item.spot.tel}" do
                i.fas.fa-phone-volume
                = item.spot.tel
          - if item.spot.memo.present? || item.memo.present?
            div.memo
              - if item.spot.memo.present?
                div.common_memo
                  = simple_format(item.spot.memo)
              - if item.memo.present?
                div.route_memo
                  = simple_format(item.memo)
    = paginate @spots
div#bottom_nav
  ul
    li#btn_goto_top
      i.fas.fa-arrow-up
    li#btn_goto_bottom
      i.fas.fa-arrow-down
    li#btn_toggle_tags
      i.fas.fa-sticky-note